### ISSUE TITLE
Create more subgraphs

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-subgraph#16]
I need the subgraph admin (Sunil) to create a couple more subgraphs.

Currently have:
- mainnet
- arbitrum

Also want:
- [x] fantom
- [x] optimism 

Unsupported:
- evmos

https://thegraph.com/docs/en/developer/create-subgraph-hosted/#supported-networks

**Comment by alphastorm** [comment]
https://thegraph.com/hosted-service/subgraph/saddle-finance/fantom
https://thegraph.com/hosted-service/subgraph/saddle-finance/optimism
